precioManzana = int(input("Dame el precio de la manzana"))
CantidadManzana =float(input("Cuantas manzanas quieres?"))
print(precioManzana)
print(CantidadManzana)
print("Hola buenos tardes mi nombre es Gabriel el frutero")
print("total a pagar es:")
print(CantidadManzana * precioManzana)
print("Total: ", CantidadManzana * precioManzana)
print("Total: " + str(CantidadManzana * precioManzana))
print(f"Total:  {CantidadManzana * precioManzana}")
